[vars]
kernel_excludes = ["/kernel/", "/kernel_standalone/"]
no_single_excludes = ["/kernel/", "/kernel_standalone/", "/examples_standalone/", "/exercises_standalone/"]

[processor.cc_single_file]
scan_dir = "src"
include_paths = ["src/include"]
exclude_dirs = "${no_single_excludes}"

[[processor.cc_single_file.compilers]]
name = "gcc"
cc = "gcc"
cxx = "g++"
output_suffix = ".elf"
cflags = [
	"-O2",
	"-Wall",
	"-Werror",
	"-Wextra",
	"-pedantic",
]
cxxflags = [
	"-O2",
	"-Wall",
	"-Werror",
	"-Wextra",
	"-pedantic",
]

[[processor.cc_single_file.compilers]]
enabled = false
name = "clang"
cc = "clang"
cxx = "clang++"
cflags = [
	"-O2",
	"-Wall",
	"-Werror",
	"-Wextra",
	"-pedantic",
]
cxxflags = [
	"-O2",
	"-Wall",
	"-Werror",
	"-Wextra",
	"-pedantic",
]

[processor.cppcheck]
exclude_dirs = "${kernel_excludes}"
args = [
	"--error-exitcode=1",
	"--enable=warning,style,performance,portability",
	"--check-level=exhaustive",
	"--suppressions-list=.cppcheck-suppressions",
]

[processor.spellcheck]
use_words_file = true

[processor.make]
exclude_paths = ["Makefile"]
exclude_dirs = "${kernel_excludes}"

[analyzer.cpp]
exclude_dirs = ["{kernel_excludes}"]
include_paths = [
	"src/include",
	"/usr/include/mysql++",
	"/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2",
	"/usr/include/wx-3.2",
	"src/examples_standalone/gcc_precompiled_headers/include",
	"src/examples_standalone/quoted_includes/folder1",
	"/usr/lib/gcc/x86_64-linux-gnu/15/plugin/include",
]
pkg_config = [
	"gtk+-2.0",
	"gtkmm-2.4",
	"mysqlclient",
	"Qt6Widgets",
]
include_path_commands = [
]
